apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-application-service
spec:
  template:
    spec:
      containers:
        - name: ark-application-service
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /heartbeat
              port: 40200
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /heartbeat
              port: 40200
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
