apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-application-service
spec:
  template:
    spec:
      containers:
        - name: ark-application-service
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
