apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-application-service
spec:
  template:
    spec:
      containers:
        - name: ark-application-service
          image: "harbor.nuclearport.com/aircraft/ark-application-service-stage:latest"
          env:
            - name: ENV_NAME
              value: "stage"
