commonLabels:
  app: ark-application-service
namePrefix: stage-
resources:
  - ../../base
patchesStrategicMerge:
  - configmap_patch.yaml
  - deployment_patch.yaml
  - remove_hpa.yaml
  - memorylimit_patch.yaml
